config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :dogs
  # devise_for :views

  get '/dogs', to: 'dogs#index'

  get 'welcome/index', to: 'welcome#index', as: 'welcome'
  get 'welcome/about', to: 'welcome#about', as: 'about'

  root 'welcome#index'



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/dog.rb
class Dog < ActiveRecord::Base

	has_attached_file :image1, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.jpg"
    validates_attachment_content_type :image1, :content_type => /\Aimage\/.*\Z/

    has_attached_file :image2, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.jpg"
    validates_attachment_content_type :image2, :content_type => /\Aimage\/.*\Z/

    has_attached_file :image3, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.jpg"
    validates_attachment_content_type :image3, :content_type => /\Aimage\/.*\Z/


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def index
    @dog = Dog.all
  end

  def new
  	@dog = Dog.new
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def edit
  end

  def create
  	@dog = Dog.new(dog_params)
  	if @dog.save
  		flash[:notice] = 'New dog created'
  		redirect_to dogs_path(@dog)
  	else
  		flash[:alert] = 'There was a problem'
  		render :new
  	end
  end

  private

  def dog_params
  	params.require(:dog).permit(:animal_type, :name, :breed, :sex, :size, :age, :description, :location, :http, :image1, :image2, :image3)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(params.require(:user).permit(:username, :email))
			if @user.save
		         redirect_to dogs_path
		  	else
		         render :new
		  end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dogs/_form.html.erb
<%= form_for @dog, :url => new_dog_path, :html => { :multipart => true } do |f| %>
  
  	<div>
		<%= f.text_field :animal_type, placeholder: 'Animal Type' %>
	</div>
	<div>
		<%= f.text_field :breed, placeholder: 'Breed' %>
	</div>
	<div>
		<%= f.text_field :sex, placeholder: 'Male/Female' %>
	</div>
	<div>
		<%= f.text_field :size, placeholder: 'Small/Medium/Large' %>
	</div>
	<div>
		<%= f.text_field :age, placeholder: 'Baby/Young/Adult/Senior' %>
	</div>
	<div>
		<%= f.text_field :description, placeholder: 'Description' %>
	</div>
	<div>
		<%= f.text_field :location, placeholder: 'City/State' %>
	</div>
	<div>
		<%= f.text_field :http, placeholder: 'http' %>
	</div>
	<div>
  		<%= f.file_field :image1 %>
  	</div>
  	<div>
  		<%= f.file_field :image2 %>
  	</div>
  	<div>
  		<%= f.file_field :image3 %>
  	</div>
  	<div>
  		<%= f.submit %>
  	</div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Dogs#edit</h1>
<p>Find me in app/views/dogs/edit.html.erb</p>

app/views/dogs/index.html.erb
<head>
 <!-- include jQuery -->
 <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
 <!-- include Cycle2 -->
 <script src="../../assets/javascripts/jssor.slider.mini.js"></script>
</head> 
<div class="browse-logo"><%= image_tag 'adoptr-logo.png' %></div>
<div class="social-bar-browse"> 
  <ul>
    <li><div class="social-icon"><%= image_tag 'twitter-clear.png' %></div></li>
    <li><div class="social-icon"><%= image_tag 'facebook-clear.png' %></div></li>
    <li><div class="social-icon"><%= image_tag 'google-clear.png' %></div></li>
    <li><div class="social-icon"><%= image_tag 'dotdot-clear.png' %></div></li>
  </ul>
  <div class="slogan-browse"><h1>connecting good pets with good people.</h1></div>
</div>
<hr class="breakline">
<div id="browse-page" class="container-fluid">  
  <div class="row-1 col-md-12">
      <div id="slider1_container">
        <!-- Slides Container -->
        <div u="slides" class="slides">       
          <div class="img-responsive"><%= image_tag "skylar-carousel.png" %></div>
          <div class="img-responsive"><%= image_tag "skylar-carousel2.png" %></div>
          <div class="img-responsive"><%= image_tag "skylar-carousel3.png" %></div>
        </div>
      </div> 
  </div>
<div class="browse-nav">
  <ul>
    <li><div class="button-yes">&#x2713</div></li>
    <li><div class="button-no">&#x2717</div></li>
  </ul>
</div>
 <div class="row-1">
   <div class="col-md-12 stats">
     <div style="color:white"><h1>Personality</h1></div>
     <!-- Progress Bar --> 
     <div class="progress">
       <div class="bar" style="width: 85%;">age</div>
       </div>  
       <div class="progress">
       <div class="bar" style="width: 75%;">demeanor</div>
       </div>    
       <div class="progress">
       <div class="bar" style="width: 100%;">plays well with others</div>
       </div> 
       <div class="progress">
       <div class="bar" style="width: 55%;">likes children</div>
       </div> 
       <div class="bar" style="width: 85%;">needs walks</div>
       </div>  
       <div class="progress">
       <div class="bar" style="width: 75%;">drool factor</div>
       </div> 
     </div>
   </div>

 </div>

</div>

app/views/dogs/new.html.erb
<div class="logo-admin-page"><%= image_tag 'adoptr-logo.png' %></div>


<% if @dog.errors.any? %>
		<% @dog.errors.full_messages.each do |error| %>
			<p style="color: red;"><%= error %></p>
		<% end %>
	<% end %>

<div class="container">	
	<div class="row-1">
		<div class="col-lg-2 col-lg-offset-5 admin-form" style="float:none;">
			<span style="color: white"><h1>Please enter your dog's information below!</h1></span>
			<%= form_for @dog, :html => { :multipart => true } do |f| %>

				<div>
					<%= f.text_field :animal_type, value: "Dog" %>
				</div>
				<div>
					<%= f.text_field :name, placeholder: 'Name' %>
				</div>
				<div>
					<%= f.text_field :breed, placeholder: 'Breed' %>
				</div>
				<div>
					<%= f.text_field :sex, placeholder: 'Male/Female' %>
				</div>
				<div>
					<%= f.text_field :size, placeholder: 'Small/Medium/Large' %>
				</div>
				<div>
					<%= f.text_field :age, placeholder: 'Baby/Young/Adult/Senior' %>
				</div>
				<div>
					<%= f.text_area :description, placeholder: 'Description' %>
				</div>
				<div>
					<%= f.text_field :location, value: "New York, NY" %>
				</div>
				<div>
					<%= f.text_field :http, placeholder: 'http' %>
				</div>
				<div>
			  		<%= f.file_field :image1 %>
			  	</div>
			  	<div>
			  		<%= f.file_field :image2 %>
			  	</div>
			  	<div>
			  		<%= f.file_field :image3 %>
			  	</div>
			  <!-- 	<div class="submit-button"> -->
			  		<%= f.submit 'submit!' %>
			  <!-- 	</div> -->
			<% end %>
		</div>
	</div>

app/views/dogs/show.html.erb
<head>
  <!-- include jQuery -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
  <!-- include Cycle2 -->
  <script src="../../assets/javascripts/jssor.slider.mini.js"></script>
  <script type="text/javascript" src="jquery-2.1.3.js"></script>
</head>
  
 <div class="logo profile-logo"><%= image_tag 'adoptr-logo.png' %></div>
<hr class="breakline">


<div class="row-1">
  <div class="col-md-12">
    <div id="slider1_container">
      <!-- Slides Container -->
      <div u="slides" class="slides">
        <div><%= image_tag @dog.image1.url(:medium) %></div>
        <!-- if image2 is nil, do not slide -->
        <div><%= image_tag @dog.image2.url %></div>
        <!-- if image3 is nil, do not slide -->
        <div><%= image_tag @dog.image3.url %></div>
      </div>
    </div>
  </div>
</div>

<div class="row-2">
  <div class="col-md-6 stats">
    <div class="lead"><h2>personality</h2></div>
    <!-- Progress Bar --> 
    <div class="progress">
      <div class="bar" style="width: 85%;"><%= @dog.age %></div>
      </div>  
      <div class="progress">
      <div class="bar" style="width: 75%;">demeanor</div>
      </div>    
      <div class="progress">
      <div class="bar" style="width: 100%;">plays well with others</div>
      </div> 
      <div class="progress">
      <div class="bar" style="width: 55%;">likes children</div>
      </div> 
      <div class="bar" style="width: 85%;">needs walks</div>
      </div>  
      <div class="progress">
      <div class="bar" style="width: 75%;">drool factor</div>     
      </div> 
    </div>
    <!-- Progress Bar End --> 
  </div>
</div>

<div class="row-2">
  <div class="col-md-6">
    <div class="lead"><h1>About <%= @dog.name %></h1></div>
      <div id="dog_pro">
          <p>
          <%= @dog.animal_type %>
          <%= @dog.breed %>
          <%= @dog.sex %>
          <%= @dog.age %>
          <%= @dog.location %>
          <%= @dog.description %>
        </p>
        <p id="zoom"><%= link_to "Adopt Me", @dog.http %></p>
      </div>
  </div>
</div>

<div class="col-md-6 location">

  <!-- <h1>Location</h1>
  <p>This is the content of the article Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, nam accusamus nemo, praesentium cumque temporibus cupiditate aperiam iusto quisquam mollitia magnam eius earum, blanditiis sit. Eum totam possimus quibusdam numquam.</p> -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Adoptr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


	<%= yield %>

		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>


</body>
</html>

app/views/welcome/about.html.erb
<h1>ABOUT PAGE</h1>

app/views/welcome/index.html.erb
  <div class="logo logo-fade"><%= image_tag 'adoptr-logo.png' %></div>


<div class="bubble-box">
  <div class="bubble-sm bubble1"><%= image_tag 'betty.jpg', class:  'img-circle img-responsive, bubble' %></div>
  <div class="bubble-md2 bubble2"><%= image_tag 'brownie.jpg', class:  'img-circle img-responsive, bubble' %></div>
  <div class="bubble-lg bubble3"><%= image_tag 'skylar.jpg', class:  'img-circle img-responsive, bubble' %></div>
  <div class="bubble-md bubble4"><%= image_tag 'petra.jpg', class:  'img-circle img-responsive, bubble' %></div>
  <div class="bubble-sm bubble5"><%= image_tag 'ros.jpg', class:  'img-circle img-responsive, bubble' %></div>
  <div class="bubble-x-sm bubble6"><%= image_tag 'corgi.jpg', class:  'img-circle img-responsive, bubble' %></div>
</div>

<div class="lower-nav">
	<ul>

		<li><div class="button-login"><%= link_to "Sign Up", new_user_registration_path %> </div></li>
		<li><div class="button-signup"><%= link_to "Sign In", new_user_session_path %>
     
		<li><div class="button-browse"><%= link_to "BROWSE", dogs_path %></div></li>

</div>

<div class="social-bar">
  <div class="slogan"><h1>connecting good pets with good people.</h1></div>
  <ul>
    <li><div class="social-icon"><%= image_tag 'twitter-clear.png' %></div></li>
    <li><div class="social-icon"><%= image_tag 'facebook-clear.png' %></div></li>
    <li><div class="social-icon"><%= image_tag 'google-clear.png' %></div></li>
    <li><div class="social-icon"><%= image_tag 'dotdot-clear.png' %></div></li>
     <% if signed_in? %>
    <li><div class="button-signup"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></div></li>
    <% end %>
  </ul>

</div>